/* ============================================================================
   Gather everything the training runs produced into one file the chart page
   can read: the generations and their weights, the epoch-by-epoch fitting
   curves, the self-play results, the gating matches, the ladder against
   generation 0, and the engine benchmarks.

     node train/collect.js <log> [<log> ...]
   ============================================================================ */
var fs = require("fs"), path = require("path");
var lib = require("./lib.js");

var DIR = path.join(__dirname, "weights");
var OUT = path.join(__dirname, "..", "assets", "js", "progress-data.js");

/* ---- the weights themselves -------------------------------------------- */
var gens = fs.readdirSync(DIR)
  .map(function (f) { return /^gen-(\d+)\.json$/.exec(f); })
  .filter(Boolean).map(function (m) { return +m[1]; })
  .sort(function (a, b) { return a - b; });

var generations = gens.map(function (n) {
  var w = lib.readWeights(path.join(DIR, "gen-" + n + ".json"));
  return {
    generation: n,
    kept: n === 0 ? true : !!w.kept,
    parent: w.parent || (n ? "gen-" + (n - 1) : null),
    trainedOn: w.trainedOn || 0,
    scoreAgainstParent: n === 0 ? null : (w.scoreAgainstParent || null),
    heldOutLossBefore: w.heldOutLossBefore || null,
    heldOutLossAfter: w.heldOutLossAfter || null,
    agreementBefore: w.agreementBefore || null,
    agreementAfter: w.agreementAfter || null,
    w: w.w
  };
});

/* ---- what the logs remember -------------------------------------------- */
var epochs = {}, selfplay = {};
process.argv.slice(2).forEach(function (file) {
  if (!fs.existsSync(file)) return;
  var text = fs.readFileSync(file, "utf8");
  var current = null;
  text.split("\n").forEach(function (line) {
    var g = /^=+ generation (\d+) =+$/.exec(line.trim());
    if (g) { current = +g[1]; return; }
    if (current == null) return;

    /* "  240/240 games, 15825 positions, 162s  (crosses 97, noughts 79, drawn 64)" */
    var sp = /^\s*(\d+)\/(\d+) games, (\d+) positions, (\d+)s\s+\(crosses (\d+), noughts (\d+), drawn (\d+)\)/.exec(line);
    if (sp && sp[1] === sp[2]) {
      selfplay[current] = { games: +sp[2], positions: +sp[3], seconds: +sp[4],
                            crosses: +sp[5], noughts: +sp[6], drawn: +sp[7] };
      return;
    }
    /* "  0      1.5592     1.5625      43.0%" */
    var ep = /^\s*(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)%/.exec(line);
    if (ep) {
      (epochs[current] = epochs[current] || []).push({
        epoch: +ep[1], fit: +ep[2], held: +ep[3], agree: +ep[4]
      });
    }
  });
});

/* ---- the ladder against generation 0 ----------------------------------- */
var ladderFile = path.join(DIR, "ladder.json");
var ladder = fs.existsSync(ladderFile) ? lib.readWeights(ladderFile) : [];

/* ---- what the engine itself measured ----------------------------------- */
/* The three long matches that settled which generation to ship. The gating
   matches are 60 games, which turned out not to be enough to tell the best
   few generations apart; these are 200. */
var playoff = [
  { a: "gen 4", b: "gen 7", games: 200, score: 49.5 },
  { a: "gen 4", b: "gen 8", games: 200, score: 43.3 },
  { a: "gen 7", b: "gen 8", games: 200, score: 48.0 }
];

var benchmarks = {
  throughput: [
    { what: "plain search, uniform playouts", playoutsPerSecond: 71000 },
    { what: "first improved playout policy", playoutsPerSecond: 32000 },
    { what: "after a lookup table, without allocation", playoutsPerSecond: 46000 },
    { what: "with the learned policy and PUCT", playoutsPerSecond: 43000 }
  ],
  matches: [
    { what: "policy + solver v plain, equal playouts", games: 40, score: 67.5 },
    { what: "policy + solver v plain, equal time", games: 40, score: 52.5 },
    { what: "after optimising, equal time", games: 60, score: 62.5 },
    { what: "learned weights v hand-set, equal playouts", games: 100, score: 68.0 },
    { what: "everything v plain search, equal time", games: 100, score: 89.0 }
  ]
};

var U = lib.engine(null);
var report = {
  builtAt: new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC",
  features: U.features.names,
  generations: generations,
  epochs: epochs,
  selfplay: selfplay,
  ladder: ladder,
  playoff: playoff,
  benchmarks: benchmarks,
  shipped: U.weights.generation
};

fs.writeFileSync(OUT,
  "/* Generated by train/collect.js — every number the training runs produced. */\n" +
  "window.PROGRESS = " + JSON.stringify(report, null, 1) + ";\n");
console.log("wrote " + OUT + " (" + generations.length + " generations, " +
            Object.keys(epochs).length + " fitting curves, " +
            Object.keys(selfplay).length + " self-play runs, " +
            ladder.length + " ladder entries)");
